
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsaimslsachuffcbpyng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzYWltc2xzYWNodWZmY2JweW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Mzg3MDAsImV4cCI6MjA2MDExNDcwMH0.U2eeqsc41o5xB4dIp8N-52u3w7TqLv4viyZgK29Jb-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
