
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase-schema';

const SUPABASE_URL = "https://deeoqzyrvwudgtqcqpdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZW9xenlydnd1ZGd0cWNxcGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTU0NzgsImV4cCI6MjA1OTgzMTQ3OH0.QR9vcNevBsVNIf22Le5JAndqUhNHMVRbGwsVUftgN0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
